apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app
  namespace: troubleshoot-adv
spec:
  ingressClassName: wrong-class
  rules:
    - host: koans.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ingress-app
                port:
                  number: 80
