apiVersion: apps/v1
kind: Deployment
metadata:
  name: ready-demo
  namespace: troubleshoot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ready-demo
  template:
    metadata:
      labels:
        app: ready-demo
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /wrong
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
