apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-demo
  namespace: troubleshoot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crash-demo
  template:
    metadata:
      labels:
        app: crash-demo
    spec:
      containers:
        - name: busybox
          image: busybox:1.36
          command: ["/bin/sh", "-c", "sleep 1 && exit 1"]
