apiVersion: apps/v1
kind: Deployment
metadata:
  name: spread-demo
  namespace: cka-koans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spread-demo
  template:
    metadata:
      labels:
        app: spread-demo
    spec:
      topologySpreadConstraints:
        - maxSkew: 2
          topologyKey: CHANGE_ME
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: spread-demo
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
