apiVersion: v1
kind: Pod
metadata:
  name: app-config
  namespace: troubleshoot-adv
spec:
  containers:
    - name: busybox
      image: busybox:1.36
      command: ["sleep", "3600"]
      volumeMounts:
        - name: config
          mountPath: /etc/app/app.conf
          subPath: app.conf
  volumes:
    - name: config
      configMap:
        name: app-config
        items:
          - key: app-config
            path: app.conf
