apiVersion: v1
kind: Service
metadata:
  name: nodeport-demo
  namespace: cka-koans
spec:
  type: ClusterIP
  selector:
    app: nodeport-demo
  ports:
    - protocol: TCP
      port: 0
      targetPort: 0
      nodePort: 0
