apiVersion: v1
kind: Service
metadata:
  name: web-koans
  namespace: cka-koans
  labels:
    app: web-koans
spec:
  selector:
    app: web-koans
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
