apiVersion: v1
kind: Service
metadata:
  name: TODO
  namespace: cka-koans
  labels:
    app: CHANGE_ME
spec:
  selector:
    app: CHANGE_ME
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 0
      targetPort: 0
