apiVersion: apps/v1
kind: Deployment
metadata:
  name: memhog
  namespace: troubleshoot-adv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memhog
  template:
    metadata:
      labels:
        app: memhog
    spec:
      containers:
        - name: busybox
          image: busybox:1.36
          command: ["/bin/sh", "-c", "dd if=/dev/zero of=/dev/shm/blob bs=1M count=100 && sleep 3600"]
          resources:
            limits:
              memory: "16Mi"
            requests:
              memory: "8Mi"
