apiVersion: v1
kind: Pod
metadata:
  name: config-demo
  namespace: cka-koans
  labels:
    app: config-demo
spec:
  containers:
    - name: busybox
      image: busybox:1.36
      command: ["sleep", "3600"]
      env:
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: CHANGE_ME
              key: APP_MODE
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: CHANGE_ME
              key: PASSWORD
