apiVersion: apps/v1
kind: Deployment
metadata:
  name: taint-demo
  namespace: troubleshoot-adv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taint-demo
  template:
    metadata:
      labels:
        app: taint-demo
    spec:
      containers:
        - name: busybox
          image: busybox:1.36
          command: ["sleep", "3600"]
